# Generated by Django 4.2.7 on 2025-07-21 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('periodo', models.CharField(max_length=100, verbose_name='Período')),
                ('arquivo_pdf', models.FileField(upload_to='informativos/pdfs/', verbose_name='Arquivo PDF')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Informativo',
                'verbose_name_plural': 'Informativos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
