version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fundo_previdenciario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./funpjf-backend
    container_name: fundo_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fundo_previdenciario
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./funpjf-backend:/app
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./breezy-laravel-haven
    container_name: fundo_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./breezy-laravel-haven:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  media_volume: