# Generated by Django 4.2.7 on 2025-07-21 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(max_length=500, verbose_name='Resumo')),
                ('conteudo_completo', models.TextField(verbose_name='Conteúdo Completo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/imagens/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('publicado', 'Publicado'), ('nao_publicado', 'Não Publicado')], default='nao_publicado', max_length=15, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
