# Generated by Django 4.2.7 on 2025-07-21 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_documento', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('categoria', models.CharField(choices=[('atas', 'Atas'), ('balancetes', 'Balancetes'), ('demonstrativos', 'Demonstrativos'), ('relatórios', 'Relatórios'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('data_documento', models.DateField(verbose_name='Data do Documento')),
                ('arquivo_pdf', models.FileField(upload_to='transparencia/pdfs/', verbose_name='Arquivo PDF')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Documento de Transparência',
                'verbose_name_plural': 'Documentos de Transparência',
                'ordering': ['-data_documento'],
            },
        ),
    ]
