# Generated by Django 4.2.7 on 2025-07-21 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_certificacao', models.CharField(max_length=200, verbose_name='Título da Certificação')),
                ('orgao_emissor', models.CharField(max_length=200, verbose_name='Órgão Emissor')),
                ('valido_ate', models.DateField(verbose_name='Válido Até')),
                ('arquivo_pdf', models.FileField(upload_to='certificacoes/pdfs/', verbose_name='Arquivo PDF')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['-valido_ate'],
            },
        ),
    ]
