# Generated by Django 4.2.7 on 2025-07-21 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo_documento', models.CharField(choices=[('balancete', 'Balancete'), ('relatorio', 'Relatório'), ('demonstrativo', 'Demonstrativo'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo de Documento')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivo_pdf', models.FileField(upload_to='contabilidade/pdfs/', verbose_name='Arquivo PDF')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Documento Contábil',
                'verbose_name_plural': 'Documentos Contábeis',
                'ordering': ['-data'],
            },
        ),
    ]
